hello: world

server:
  prot: 8081

#spring:
#  redis:
#    open: true
#    host: 192.168.1.4
#      database: 0
#      password:
#      port: 6379

spring:
  redis:
    # Redis数据库索引（默认为0）
    database: 1
    # Redis服务器地址
    host: 192.168.1.4
    # Redis服务器连接端口
    port: 6379
    # Redis服务器连接密码（默认为空）
    password:


#logging:
#  level:
#    com:
#      yzw:
#        jmetersampler:
#          mapper: debug



#spring:
#  datasource:
#    username: mouw
#    password: dkal109iduqykcs
#    url: jdbc:mysql://mysql.dev208.56qq.com:3306/testbigdata?useUnicode=true&characterEncoding=UTF-8&useOldAliasMetadataBehavior=true&autoReconnect=true
#    driver-class-name: com.mysql.jdbc.Driver
#
#mybatis:
#  mapper-locations: classpath:mapper/*Mapper.xml
#  type-aliases-package: com.huilu.testplatform.entity

#showSql
logging:
  level:
    com:
      yzw:
        jmetersampler:
          mapper: debug

